#!/usr/bin/env bash
# Contains utility functions for use in other scripts

# Move the SCL-enabled python values into environment variables locally
# for overriding purposes 
# SCL installs of python 3.3
function update-configuration {

    sclpath=$(dirname $(scl enable python33 "which python"))
    echo "$VIRTUAL_ENV/bin:$OPENSHIFT_GEO_DIR/bin:$sclpath" > $ENV_PATH/OPENSHIFT_PYTHON_PATH_ELEMENT

    local ld_path=$(LD_LIBRARY_PATH="" scl enable python33 "printenv LD_LIBRARY_PATH")
    path_append ${LD_LIBRARY_PATH:-:} ${ld_path:-:} > $ENV_PATH/LD_LIBRARY_PATH

    local man_path=$(MANPATH="" scl enable python33 "printenv MANPATH")
    path_append ${MANPATH:-:} ${man_path:-:} > $ENV_PATH/MANPATH

    local xdg_data_dirs=$(XDG_DATA_DIRS="" scl enable python33 "printenv XDG_DATA_DIRS")
    path_append ${XDG_DATA_DIRS:-:} ${xdg_data_dirs:-:} > $ENV_PATH/XDG_DATA_DIRS

    local pkg_config_path=$(PKG_CONFIG_PATH="" scl enable python33 "printenv PKG_CONFIG_PATH")
    path_append ${PKG_CONFIG_PATH:-:} ${pkg_config_path:-:} > $ENV_PATH/PKG_CONFIG_PATH
}
